# dindrunnerdeployment.yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: k8s-dind-action-runner
  namespace: actions-runner-system
spec:
  #replicas: 1
  template:
    spec:
      labels:
        - meta-dind
        - self-hosted
        - linux
        - x64
      image: summerwind/actions-runner-dind
      nodeSelector:
        role: agent
        os: amazon-linux
        kubernetes.io/os: linux
        memory: 64GB
      dockerdWithinRunnerContainer: true
      organization: hadeaninc
      env: []
